[project]
name = "hackass"
version = "1.0.0"
authors = [
  { name="Simon Nganga", email="theedushbag@gmail.com" },
]
description = "hackass is an assembler for the Hack machine; from HackASM to HackExecutable."
requires-python = ">=3.11"

[project.scripts]
hasm = "hackass.main:main"

